cp *.tar /mnt/data/yuboqi/code_all/h_learning/kinds_inter/short_mm1m
cp *.tar /mnt/data/yuboqi/code_all/h_learning/kinds_inter/short_mm2m
cp *.tar /mnt/data/yuboqi/code_all/h_learning/kinds_inter/short_ms1m/
cp *.tar /mnt/data/yuboqi/code_all/h_learning/kinds_inter/short_sm2m/
cp *.tar /mnt/data/yuboqi/code_all/h_learning/kinds_intra/short_sm2m/
cp *.tar /mnt/data/yuboqi/code_all/h_learning/kinds_intra/short_ms1m/
cp *.tar /mnt/data/yuboqi/code_all/h_learning/kinds_intra/short_mm1m/
cp *.tar /mnt/data/yuboqi/code_all/h_learning/kinds_intra/short_mm2m/
cp *.tar /mnt/data/yuboqi/code_all/h_learning/kinds_intra_long/short_mm2m/
cp *.tar /mnt/data/yuboqi/code_all/h_learning/kinds_intra_long/short_mm1m/
cp *.tar /mnt/data/yuboqi/code_all/h_learning/kinds_intra_long/short_ms1m/
cp *.tar /mnt/data/yuboqi/code_all/h_learning/kinds_intra_long/short_sm2m/
